### PR TITLE
fix(neotest): Fix bug in neotest by checking for existing library key table 

### LINKED ISSUE #406: Add neodev integration for neotest community pack
The [neotest README](https://github.com/nvim-neotest/neotest#configuration) says:

>It is highly recommended to use [neodev.nvim](https://github.com/folke/neodev.nvim) to enable type checking for neotest to get type checking, documentation and autocompletion for all API functions.
>
> ```lua
> require("neodev").setup({
>   library = { plugins = { "neotest" }, types = true },
>   ...
> })
> ```

Could we please add this to the astrocommunity's neotest pack [here](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/test/neotest/init.lua)?

### PR DESCRIPTION
**Pull request by Uzaaft**
I’d let mehalter double check this one

Closes #406

### CODE REVIEW

File: lua/astrocommunity/test/neotest/init.lua [hunk 1]
```diff
@@ -8,8 +8,12 @@ return {
...
       "folke/neodev.nvim",
       opts = function(_, opts)
-        opts.library.plugins = require("astronvim.utils").list_insert_unique(opts.library.plugins, "neotest")
-        opts.library.types = true
+        return require("astronvim.utils").extend_tbl(opts, {
+          library = {
+            plugins = { "neotest" },
+            types = true,
+          },
+        })
```
Comment (mehalter) [inline lua/astrocommunity/test/neotest/init.lua:16]:
```suggestion
        opts.library = opts.library or {}
        opts.library.plugins = require("astronvim.utils").list_insert_unique(opts.library.plugins, "neotest")
        opts.library.types = true
```

**Review by mehalter — CHANGES_REQUESTED** [review]
This is the incorrect approach @Uzaaft . The original method was correct, we just forgot to check if the library key was a table or not

**Review by mehalter — APPROVED** [review]
LGTM!

File: lua/astrocommunity/test/neotest/init.lua [hunk 2]
```diff
@@ -8,6 +8,7 @@ return {
     {
       "folke/neodev.nvim",
       opts = function(_, opts)
+        opts.library = opts.library or {}
         opts.library.plugins = require("astronvim.utils").list_insert_unique(opts.library.plugins, "neotest")
```
Comment (mehalter) [inline lua/astrocommunity/test/neotest/init.lua:12]:
```suggestion
        if opts.library.plugins ~= true then
          opts.library.plugins = require("astronvim.utils").list_insert_unique(opts.library.plugins, "neotest")
        end
```

**Review by mehalter — CHANGES_REQUESTED** [review]
`library.plugins` can technically be `true` which I believe enables all plugins

File: lua/astrocommunity/test/neotest/init.lua (hunk 2 above)
Comment (mehalter) [reply lua/astrocommunity/test/neotest/init.lua:12]: Docs for reference: https://github.com/folke/neodev.nvim#%EF%B8%8F-configuration

**Review by mehalter — APPROVED** [review]
LGTM!
