### PR TITLE
fix(leap-nvim): Fix cursor invisible bug on nvim 0.10+

### LINKED ISSUE #1219: Leap cursor visibility workaround makes cursor invisible on nvim 0.10+
https://github.com/AstroNvim/astrocommunity/blob/f4a19c410fdcf778d44a8b9ece55e529df7a0274/lua/astrocommunity/motion/leap-nvim/init.lua#L9-L25

These should be conditional on nvim < 0.10

### PR DESCRIPTION
**Pull request by ALameLlama**
Closes #1219 

## 📑 Description

The workaround breaks on 0.10+ so I've made it only apply when the minor version is less than 10.

### CODE REVIEW

File: lua/astrocommunity/motion/leap-nvim/init.lua [hunk 1]
```diff
@@ -5,26 +5,28 @@ return {
...
+                  event = "User",
+                  pattern = "LeapLeave",
+                  callback = function()
+                    vim.cmd.hi("Cursor", "blend=0")
+                    vim.opt.guicursor:remove { "a:Cursor/lCursor" }
+                  end,
+                },
+              },
+            }
+          or {},
```
Comment (Uzaaft) [inline lua/astrocommunity/motion/leap-nvim/init.lua:29]: Is this vim.version() api available on 0.9?

Comment (ALameLlama) [reply lua/astrocommunity/motion/leap-nvim/init.lua:29]: Was added in 0.9 by the looks of it https://neovim.io/doc/user/news-0.9.html

> Added [vim.version](https://neovim.io/doc/user/lua.html#vim.version) for parsing and comparing version strings conforming to the semver specification.

**Review by Uzaaft — APPROVED** [review]

**Review by Uzaaft — APPROVED** [review]
